apiVersion: apps/v1
kind: Deployment
metadata:
  name: account microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Account Microservice
  template:
    metadata:
      labels:
        app: Account Microservice
    spec:
      containers:
      - name: Account_Microservicerepos
        image: anujretailbankingcr.azurecr.io/Account_Microservicerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: account microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Account Microservice
